version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: script/deploy.sh
      timeout: 120
      runas: root
    - location: script/switch.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: script/valid.sh
      timeout: 60
      runas: root