name: ci-main

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Create properties
        run: |
          cd ./src/main/resources
          touch application.yml
          touch application.properties
          echo "${{ secrets.APPLICATION_YAML }}" >> application.yml
          echo "${{ secrets.APPLICATION_PROPERTIES }}" >> application.properties

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash